
const ADD_WEATHER = 'ADD_WEATHER';
const EDIT_WEATHER = 'EDIT_WEATHER';
const DELETE_WEATHER = 'DELETE_WEATHER';
const SET_WEATHER = 'SET_WEATHER';
const REMOVE_WEATHER = 'REMOVE_WEATHER';
const SET_WEATHERS = 'SET_WEATHERS';

export { ADD_WEATHER, EDIT_WEATHER, DELETE_WEATHER, SET_WEATHER, REMOVE_WEATHER,SET_WEATHERS};